version: "3"
services:
  app:
    image: hello-world
    ports:
      - "80:80"
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: hydromet
    ports:
      - "5432:5432"
    restart: 'always'
