# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:9
    restart: always
    environment:
      POSTGRES_PASSWORD: hydromet
    ports:
      - 5432:5432
   
    volumes:
      - c:\data\db:/data/db

      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
   
  master:
    image: master 
      
  
   